### ISSUE TITLE
SSLError when searching 

### ISSUE THREAD

**Issue by AlaaZarifa** [cesarferreira/alfi#17]
**After installing the gem successfully..**

```
C:\DevKit>chcp 1252
Active code page: 1252

C:\DevKit>gem install alfi
Fetching: json-2.0.4.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
Successfully installed json-2.0.4
Fetching: alfi-0.5.0.gem (100%)
Successfully installed alfi-0.5.0
Parsing documentation for json-2.0.4
Installing ri documentation for json-2.0.4
Parsing documentation for alfi-0.5.0
Installing ri documentation for alfi-0.5.0
Done installing documentation for json, alfi after 6 seconds
2 gems installed
```

**Then I tried to search for any library.. this error shows??**

```
C:\DevKit>alfi picasso
Searching...
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from C:/Ruby22/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:923:in `connect'
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:1375:in `request'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/alfi-0.5.0/lib/alfi/providers/bintray.rb:40:in `call'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/alfi-0.5.0/lib/alfi/search.rb:16:in `block in call'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/alfi-0.5.0/lib/alfi/search.rb:16:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/alfi-0.5.0/lib/alfi/search.rb:16:in `call'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/alfi-0.5.0/lib/alfi/cli.rb:24:in `call'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/alfi-0.5.0/bin/alfi:5:in `<top (required)>'
        from C:/Ruby22/bin/alfi:23:in `load'
        from C:/Ruby22/bin/alfi:23:in `<main>'
```

**Comment by cesarferreira** [comment]
are you behind some firewall?
