### ISSUE TITLE
Crash when searching for hyphen or any other special character

### ISSUE THREAD

**Issue by MarsVard** [cesarferreira/alfi#2]
~/Downloads [ alfi active-android                                                                                                             ] 
Searching...
/Library/Ruby/Gems/2.0.0/gems/alfi-0.3.2/lib/alfi.rb:35:in `fetch_results': undefined method`[]' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/alfi-0.3.2/lib/alfi.rb:98:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/alfi-0.3.2/bin/alfi:5:in`<top (required)>'
    from /usr/bin/alfi:23:in `load'
    from /usr/bin/alfi:23:in`<main>'

**Comment by MarsVard** [comment]
Thank you!
